name: Argocd testing

on:
  push:
    branches:
      - main

jobs:
  # build_dev:
  #   runs-on: [ self-hosted, runnerlab, develop ]

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  build_and_push_image:
    name: build docker images and push to repository
    runs-on: [ self-hosted, runnerlab, develop ]
    needs: ['build_dev']
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup docker build
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: login to github packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build, tag, and push image to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: 
            ${{ secrets.DOCKER_USER }}/nginximages:${{ github.sha }}
            #${{ secrets.DOCKER_USER }}/nginximages:${{ github.sha }}
          #push: ${{ github.ref == 'refs/heads/main' }}
          push: true
          
      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage_argocd:
    runs-on: [ self-hosted, runnerlab, develop ]
    needs: ['build_dev','build_and_push_image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ThienNguyen2207/devopsrepo 
          ref: "main"
          token: ${{ secrets.TOKEN }}

      - name: setup git config
        run: /
          git config --global user.email "minhthien@gmail.com"
          git config --glocal user.name "ThienNguyen2207"
          echo ${{ github.sha }}
          sed -ri  "s/^(\s*)(repository\s*:\s*nginx\s*$)/\1repository:(\s)dockerminhthien2207\/nginximages/g" nginxapp/dev-values.yaml
          git add -A
          git commit -am " update images"
      
      - name: push origin main
        run: git push origin main