name: Build source code

on:
  push:
    branches:
      - main


jobs:
  deploy_to_develop:
    runs-on: [ self-hosted, develop, backend ]
    if: ${{ github.ref_name == 'main' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2      

    - name: Login to dockerhub
      uses: dockerminhthien2207/.....
      with:
        username: 
        password: 

    - name: Build, tag, and push image to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags:
          ...
        push:
        ...

  update-manifest-stage_argocd
    runs-on: ubuntu-latest
    needs: [....]
    steps:
      - uses: action/checkout@3
        with:
          repository:
          ref: "main"
          token: ${{secret.TOKEN}}

      - name: setup git config
        run: /
        ...

      - run: echo ${{ github }}
      - run: git push origin main           